services:
  postgres:
    image: postgres:16-alpine
    container_name: jobtrackr-pg
    restart: unless-stopped
    networks:
      - jobtrackr-network
    environment:
      POSTGRES_DB: jobtrackr
      POSTGRES_USER: jobtrackr
      POSTGRES_PASSWORD: jobtrackr
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U jobtrackr"]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    container_name: jobtrackr-pgadmin
    restart: unless-stopped
    networks:
      - jobtrackr-network
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@jobtrackr.com
      PGADMIN_DEFAULT_PASSWORD: adminpassword
    ports:
      - "8082:80"

  backend:
    build: ./backend
    restart: unless-stopped
    networks:
      - jobtrackr-network
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: jobtrackr
      DB_USER: jobtrackr
      DB_PASSWORD: jobtrackr
      JWT_SECRET: ${JWT_SECRET:'IIbQMGSWlUR6Zz2uVntBbjQBtpXICIwmwxAelMgFOZUl0GjUH5ah9UoV9d8uP6PBNLHwqjOYGKw3yaPG+Mcog9g==}
      JWT_EXPIRATION_MS: 7200000
      MANAGEMENT_PORT: 8081
    ports:
      - "8080:8080"
      - "8081:8081"

  frontend:
    build: ./frontend
    restart: unless-stopped
    networks:
      - jobtrackr-network
    depends_on:
      - backend
    ports:
      - "4200:80"

  prometheus:
    image: prom/prometheus:v3.0.1
    restart: unless-stopped
    networks:
      - jobtrackr-network
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:11.4.0
    restart: unless-stopped
    networks:
      - jobtrackr-network
    depends_on:
      - prometheus
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_AUTH_ANONYMOUS_ENABLED: "false"
    volumes:
      - ./monitoring/grafana-provisioning/datasources:/etc/grafana/provisioning/datasources:ro
      - grafana-data:/var/lib/grafana
    ports:
      - "3000:3000"

volumes:
  pgdata:
  prometheus-data:
  grafana-data:

# Déclaration du réseau personnalisé créé manuellement en ligne de commande
networks:
  jobtrackr-network:
    external: true
